Alert component
kacpi52/sidebar_template pull request #11
Opened 2022-04-14 09:37 UTC by kacpi52

ten do sprawdzenia

2022-04-20 21:36 UTC, wbluecloud requested changes
Zobacz 2 sugestie.
Jak prawidłowo tworzyć biblioteki komponentow?
Czemu zmiany są w shop.jsx?

2022-04-20 21:36 UTC, wbluecloud commented on src/Components/AlertBox/AlertBox.scss
> +    background-color: rgb(3, 6, 20);
dobrze jest zdefiniowac palete kolorow

2022-04-20 21:36 UTC, wbluecloud commented on src/Components/AlertBox/AlertBox.scss
> +    text-align: right;
podobnie z czcionkami

2022-04-21 12:34 UTC, wbluecloud commented on src/Components/AlertBox/AlertBox.jsx
> +      <span className="AlertItem__button">X</span>
`X` to mial byc przycisk do zamykania

2022-04-22 14:16 UTC, kacpi52 commented
nie zmienilem co prawda tego stylowania dla tego istniejacego przycisku ale to przy okazji rozmowy przez tel sie chcialem dopytac o to co i jak .

2022-04-22 14:23 UTC, wbluecloud requested changes
dobrze z importami 👍 
jedno do przemyślenia 
kolory do poprawy 👎

2022-04-22 14:23 UTC, wbluecloud commented on src/Components/SidebarMenu/index.js
> +import DropDown from "./DropDown";
nie ma tego pliku

2022-04-22 14:23 UTC, wbluecloud commented on src/Components/index.js
> +export { AlertBox, LoginPanel, ShopItem, Menu, TopList };
👍

2022-04-22 14:23 UTC, wbluecloud commented on src/Components/index.js
> +import { Menu } from "../Components/SidebarMenu/index";
czemu to jest w klamrach a pozostałe nie? (dobrze, ale musisz mi wytłumaczyć)

2022-04-22 14:23 UTC, wbluecloud commented on src/Utils/FontsBackgrounds.jsx
> +  color: "rgb(232, 190, 190)",
kolory. Osobny obiekt/plik/komponent/funkcja gdzie są zdefiniowane

2022-04-27 23:10 UTC, wbluecloud requested changes
kilka rzeczy i nowy branch

2022-04-27 23:10 UTC, wbluecloud commented on public/index.html
> +    />
👍

2022-04-27 23:10 UTC, wbluecloud commented on readme
> +https://template-tires-x.herokuapp.com
👍

2022-04-27 23:10 UTC, wbluecloud commented on src/Utils/FontsBackgrounds.scss
> +$fontAlert: "Fira Sans";
👍

2022-04-27 23:10 UTC, wbluecloud commented on src/Components/index.js
> +import { Menu } from "../Components/SidebarMenu/index";
jeszcze na to mi nie odpowiedziałes

2022-05-17 13:16 UTC, wbluecloud approved these changes
zmerguj ten adres

2022-05-17 13:16 UTC, wbluecloud commented on readme
> +https://template-tires-x.herokuapp.com
zmerguj to

2022-07-28 20:40 UTC, merged