alert component rebuild
kacpi52/sidebar_template pull request #12
Opened 2022-04-29 15:01 UTC by kacpi52

przebudowany komponent, ale mam problem z usunieciem danego alertu przez przycisk . probowalem slice() ale wtedy zostaje mi ten ktory usuwam.

2022-04-29 15:07 UTC, kacpi52 commented
te najnowsze zmiany wrzcuilem tez na hosting

2022-05-10 00:59 UTC, wbluecloud requested changes
Zmiany w dobrym kierunku, ale musisz poprawic

2022-05-10 00:59 UTC, wbluecloud commented on src/pages/GamePage.jsx
> +  }, [alertContent]);
`useEffect` nie powinien renderować

2022-05-16 18:28 UTC, wbluecloud requested changes
musisz poprawić wyświetlanie

2022-05-16 18:28 UTC, wbluecloud commented on src/pages/GamePage.jsx
> +  );
znowu wrzucasz caly komponent do tablicy. Do tablicy wrzucasz tylko obiekt z parametrami, a nie cały komponent

2022-07-28 20:38 UTC, merged